config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  resources :users, only: [:show] do
    resource :items, only: [:create, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  protected
  def after_sign_in_path_for(user)
    user_path(current_user)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    @item = @user.items.build(items_params)

    if @item.save
      flash[:notice] = "Item was saved successfully."
      redirect_to @user
    else
      flash.now[:alert] = "Error creating item. Please try again."
      redirect_to @user
    end
  end

  def destroy
    @user = current_user
    @item = @user.items.find(params[:user_id])

    if @item.destroy
      flash[:notice] = "Item was deleted successfully."
    else
      flash[:alert] = "Item could not be deleted. Try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

private
  def items_params
    params.require(:item).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [user, item] do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "url" %>
    </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= content_tag :tr, class: "media", id: "item-#{item.id}" do %>
  <div class="media">
    <div class="media-body">
      <td><%= item.name %></td>
      <td><%= link_to "", user_items_path(item), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
      <td><%= distance_of_time_in_words(Time.now, item.created_at+7.days)%></td>
    </div>
  </div>
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-<%= @item.id %>').hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type= 'button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checkitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
      <% end %>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>
  </div>

  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h2>Hello, <%= @user.email %>!</h2>

<h3>My Items</h3>

<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th> Description </th>
              <th> Complete </th>
              <th> Time Remaining </th>
            </tr>
          </thead>
          <tbody>
            <tr class='js-items'>
              <% @items.each do |item| %>
                <%= render partial: 'items/item', locals: { item: item } %>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <% if current_user %>
      <div class='new-item'>
        <%= render 'items/form', item: Item.new, user: @user %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Checkitoff</h1>
<p>Created by: Camille </p>

app/views/welcome/index.html.erb
<h1>Welcome to Checkitoff</h1>
<p>This is the home page for Checkitoff.</p>